[module.hugoVersion]
min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hbstack/form"

[[module.imports]]
path = "github.com/hugomods/recaptcha-v2"

[params.hb.contact]
endpoint = ""
file = false
recaptcha_sitekey = ""

# [params.hugopress.modules.hb-contact.hooks.body-end]
# cacheable = true
